### PR TITLE
Fixed wrong calculation of the zone-id in LocalZoneIndex.java

### PR DESCRIPTION
**Pull request by jbuchsteiner**
Forum thread: https://hub.jmonkeyengine.org/t/sim-ethereal-zone-radius-bug/39335/4

### CODE REVIEW

**Comment by assofohdz** [comment]
Any chance this can be merged?

**Comment by pspeed42** [comment]
I want to but I need to have time to add the entry to the release notes file and test it myself, etc..

**Comment by pspeed42** [comment]
I will try to do it soon.

**Comment by pspeed42** [comment]
Forgot to get this one in before the 1.30 release... but at least it's in now.  Sorry for the delay.

It will go into the next release.

**Pull request merged**
